---
abstract: 'Add an arbitrary tag to an attribute'
author:
  - 'Aaron Cohen <aarondcohen@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker::CPANfile: 0.05
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Trait-Tag
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  ExtUtils::MakeMaker::CPANfile: 0
  FindBin: 0
  Moose: 0
  Set::Functional: 0
  Test::Most: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://github.com/aarondcohen/perl-moosex-trait-tag/issues
  homepage: http://github.com/aarondcohen/perl-moosex-trait-tag
  repository: git://github.com/aarondcohen/perl-moosex-trait-tag.git
version: 1.03
